language: python
python:
- '3.6'
install:
- pip install .
- pip install codecov
script:
- coverage run setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  username: dexter2206
  password:
    secure: "YAWhkL6wO7oxBqEc12soFBiybHwWRgdzjoVmASz50tt3Hd2qJMnxNkFRRgLTI6nDgSwMnSLOZ3brlqiVdPdYZ6FsO2yJytJyN2iIlkrfpIDbWlOR6XuuRcx7QFpsLepEKp6aOFvhSzVpPTIou+pCjjTrlRzrM2COvc5RCE9aaXvk33HUTZeTe8oy4M5SCvwyCT0fDrSsYhWKKzpCWt80SqtCxIBIbNppUJ3ugyw2YBMw1+GwY906GhV9T6LzYyRn4YuToGuvOcu0fNkDk/JX5ZY1K/V0mX92yGTWCUlcBGvBDzGKNjnpuUES4h5UmLhhEavmuEqX5lQtPgB8Bano0SRtbI6LPOz1XTvU5wKuFmujqP3KpyV+PMqboHlT0SvtuxVSGl1BGtZNVBjay8vuJ9WJVFQjj3ejApVO9yWv1Nm7ebGRpd7Q2jhZsroJW4VXJVqxPT8B20jAZe6uyPGMPTM8TBwkBwetNzIBl3n6g9cuwYumLhtQ1jVCjvq64BoJnqlxTFxLR4KmWsjXAj4D9NzHxV4umXGg7CFd6A4Hkxflra18ScQj9iejaZE5GJYz0haUr63lV/JQ3rdp/IkOhUOIe1audZgkt3MbnHjyzJAbrh1sUjwW7jPglOSgLBWHCSrn+xYw8JAJE+3jb6M1B9Rqq2dahfxFbk+0rLN/YEc="
  on:
    tags: true
